name: govulncheck

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ~1.19

scan:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
