name: govulncheck

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '>=1.19.3'
      cache:
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  scan:
    runs-on: [self-hosted, linux, x64]
    container: 
      image: golang:latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3
        with:
          go-version: ${{ inputs.go-version }}
          cache: ${{ inputs.cache }}
      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
