name: govulncheck

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ~1.19

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: read
      packages: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
