name: metatest

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  govulncheck:
    uses: caarlos0/meta/govulncheck.yml@main
    with:
      cache: false
      go-version: '>=1.19.1'
  semgrep:
    uses: caarlos0/meta/semgrep.yml@main
  ruleguard:
    uses: caarlos0/meta/ruleguard.yml@main
    with:
      cache: false
      go-version: '>=1.19.1'

