name: ruleguard

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ~1.19

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
      - name: install ruleguard
        run: |
          go install -v github.com/quasilyte/go-ruleguard/cmd/ruleguard@latest
          go get -v -u github.com/quasilyte/go-ruleguard/dsl@latest
      - name: get rules
        run: git clone https://github.com/dgryski/semgrep-go.git /tmp/rules
      - name: run
        run: ruleguard -c=0 -rules /tmp/rules/ruleguard.rules.go ./...
