name: semgrep

on:
  workflow_call: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: get rules
        run: git clone https://github.com/dgryski/semgrep-go.git /tmp/rules
      - name: run
        run: semgrep -f /tmp/rules .

