name: semgrep

on:
  workflow_call: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      contents: read
      id-token: read
      packages: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - name: get rules
        run: git clone https://github.com/dgryski/semgrep-go.git /tmp/rules
      - name: run
        run: semgrep scan --error --enable-nosem -f /tmp/rules .

