name: semgrep

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  scan:
    runs-on: [self-hosted, linux, x64]
    container:
      image: docker.io/returntocorp/semgrep
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          repository: dgryski/semgrep-go
          path: rules
      - name: semgrep
        run: semgrep scan --error --enable-nosem -f ./rules .

