name: semgrep

on:
  workflow_call: {}

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
        with:
          repository: dgryski/semgrep-go
          path: rules
      - name: semgrep
        run: semgrep scan --error --enable-nosem -f ./rules .

